### ISSUE TITLE
[Bug]: Cannot suppress certain warnings

### ISSUE THREAD

**Issue by catalinaperalta** [microsoft/typespec#6110]
### Describe the bug

Ran into the following warnings+errors when compiling [this spec](https://github.com/Azure/azure-rest-api-specs/tree/feature/blob-tsp/specification/storage/Microsoft.BlobStorage) and can't suppress them:

```bash
PS C:\Users\caperal\repos\azure-rest-api-specs\specification\storage\Microsoft.BlobStorage> tsp compile .                 
TypeSpec compiler v0.64.0

Diagnostics were reported during compilation:

../C:/Users/caperal/repos/azure-rest-api-specs/node_modules/@typespec/compiler/lib/intrinsics.tsp:191:7 - warning @azure-tools/typespec-autorest/unsupported-param-type: Parameter can only be represented as primitive types in swagger 2.0. Information is lost for part 'x-ms-meta'.
> 191 | model Record<Element> {}
      |       ^^^^^^
  ../C:/Users/caperal/repos/azure-rest-api-specs/specification/storage/Microsoft.BlobStorage/models.tsp:208:36 - occurred while instantiating template
  > 208 |   @Xml.name("Metadata") metadata?: Record<string>;
        |                                    ^^^^^^^^^^^^^^
../C:/Users/caperal/repos/azure-rest-api-specs/node_modules/@typespec/compiler/lib/intrinsics.tsp:191:7 - warning @azure-tools/typespec-autorest/unsupported-param-type: Parameter can only be represented as primitive types in swagger 2.0. Information is lost for part 'metadata'.
> 191 | model Record<Element> {}
      |       ^^^^^^
  ../C:/Users/caperal/repos/azure-rest-api-specs/specification/storage/Microsoft.BlobStorage/models.tsp:208:36 - occurred while instantiating template
  > 208 |   @Xml.name("Metadata") metadata?: Record<string>;
        |                                    ^^^^^^^^^^^^^^
../C:/Users/caperal/repos/azure-rest-api-specs/node_modules/@typespec/compiler/lib/intrinsics.tsp:191:7 - warning @azure-tools/typespec-autorest/unsupported-param-type: Parameter can only be represented as primitive types in swagger 2.0. Information is lost for part 'x-ms-meta'.
> 191 | model Record<Element> {}
      |       ^^^^^^
  ../C:/Users/caperal/repos/azure-rest-api-specs/specification/storage/Microsoft.BlobStorage/models.tsp:208:36 - occurred while instantiating template
  > 208 |   @Xml.name("Metadata") metadata?: Record<string>;
        |                                    ^^^^^^^^^^^^^^
../C:/Users/caperal/repos/azure-rest-api-specs/node_modules/@typespec/compiler/lib/intrinsics.tsp:191:7 - warning @azure-tools/typespec-autorest/unsupported-param-type: Parameter can only be represented as primitive types in swagger 2.0. Information is lost for part 'metadata'.
> 191 | model Record<Element> {}
      |       ^^^^^^
  ../C:/Users/caperal/repos/azure-rest-api-specs/specification/storage/Microsoft.BlobStorage/models.tsp:208:36 - occurred while instantiating template
  > 208 |   @Xml.name("Metadata") metadata?: Record<string>;
        |                                    ^^^^^^^^^^^^^^
../C:/Users/caperal/repos/azure-rest-api-specs/node_modules/@typespec/compiler/lib/intrinsics.tsp:191:7 - warning @azure-tools/typespec-autorest/unsupported-param-type: Parameter can only be represented as primitive types in swagger 2.0. Information is lost for part 'objectReplicationRules'.
> 191 | model Record<Element> {}
      |       ^^^^^^
  ../C:/Users/caperal/repos/azure-rest-api-specs/specification/storage/Microsoft.BlobStorage/models.tsp:208:36 - occurred while instantiating template
  > 208 |   @Xml.name("Metadata") metadata?: Record<string>;
        |                                    ^^^^^^^^^^^^^^
../C:/Users/caperal/repos/azure-rest-api-specs/node_modules/@typespec/compiler/lib/intrinsics.tsp:191:7 - warning @azure-tools/typespec-autorest/unsupported-param-type: Parameter can only be represented as primitive types in swagger 2.0. Information is lost for part 'metadata'.
> 191 | model Record<Element> {}
      |       ^^^^^^
  ../C:/Users/caperal/repos/azure-rest-api-specs/specification/storage/Microsoft.BlobStorage/models.tsp:208:36 - occurred while instantiating template
  > 208 |   @Xml.name("Metadata") metadata?: Record<string>;
        |                                    ^^^^^^^^^^^^^^
../C:/Users/caperal/repos/azure-rest-api-specs/node_modules/@typespec/compiler/lib/intrinsics.tsp:191:7 - warning @azure-tools/typespec-autorest/unsupported-param-type: Parameter can only be represented as primitive types in swagger 2.0. Information is lost for part 'objectReplicationRules'.
> 191 | model Record<Element> {}
      |       ^^^^^^
  ../C:/Users/caperal/repos/azure-rest-api-specs/specification/storage/Microsoft.BlobStorage/models.tsp:208:36 - occurred while instantiating template
  > 208 |   @Xml.name("Metadata") metadata?: Record<string>;
        |                                    ^^^^^^^^^^^^^^
../C:/Users/caperal/repos/azure-rest-api-specs/node_modules/@typespec/compiler/lib/intrinsics.tsp:191:7 - warning @azure-tools/typespec-autorest/unsupported-param-type: Parameter can only be represented as primitive types in swagger 2.0. Information is lost for part 'metadata'.
> 191 | model Record<Element> {}
      |       ^^^^^^
  ../C:/Users/caperal/repos/azure-rest-api-specs/specification/storage/Microsoft.BlobStorage/models.tsp:208:36 - occurred while instantiating template
  > 208 |   @Xml.name("Metadata") metadata?: Record<string>;
        |                                    ^^^^^^^^^^^^^^
../C:/Users/caperal/repos/azure-rest-api-specs/node_modules/@typespec/compiler/lib/intrinsics.tsp:191:7 - warning @azure-tools/typespec-autorest/unsupported-param-type: Parameter can only be represented as primitive types in swagger 2.0. Information is lost for part 'objectReplicationRules'.
> 191 | model Record<Element> {}
      |       ^^^^^^
  ../C:/Users/caperal/repos/azure-rest-api-specs/specification/storage/Microsoft.BlobStorage/models.tsp:208:36 - occurred while instantiating template
  > 208 |   @Xml.name("Metadata") metadata?: Record<string>;
        |                                    ^^^^^^^^^^^^^^
../C:/Users/caperal/repos/azure-rest-api-specs/node_modules/@typespec/compiler/lib/intrinsics.tsp:191:7 - warning @azure-tools/typespec-autorest/unsupported-param-type: Parameter can only be represented as primitive types in swagger 2.0. Information is lost for part 'x-ms-meta'.
> 191 | model Record<Element> {}
      |       ^^^^^^
  ../C:/Users/caperal/repos/azure-rest-api-specs/specification/storage/Microsoft.BlobStorage/models.tsp:208:36 - occurred while instantiating template
  > 208 |   @Xml.name("Metadata") metadata?: Record<string>;
        |                                    ^^^^^^^^^^^^^^
../C:/Users/caperal/repos/azure-rest-api-specs/node_modules/@typespec/compiler/lib/intrinsics.tsp:191:7 - warning @azure-tools/typespec-autorest/unsupported-param-type: Parameter can only be represented as primitive types in swagger 2.0. Information is lost for part 'x-ms-meta'.
> 191 | model Record<Element> {}
      |       ^^^^^^
  ../C:/Users/caperal/repos/azure-rest-api-specs/specification/storage/Microsoft.BlobStorage/models.tsp:208:36 - occurred while instantiating template
  > 208 |   @Xml.name("Metadata") metadata?: Record<string>;
        |                                    ^^^^^^^^^^^^^^
../C:/Users/caperal/repos/azure-rest-api-specs/node_modules/@typespec/compiler/lib/intrinsics.tsp:191:7 - warning @azure-tools/typespec-autorest/unsupported-param-type: Parameter can only be represented as primitive types in swagger 2.0. Information is lost for part 'x-ms-meta'.
> 191 | model Record<Element> {}
      |       ^^^^^^
  ../C:/Users/caperal/repos/azure-rest-api-specs/specification/storage/Microsoft.BlobStorage/models.tsp:208:36 - occurred while instantiating template
  > 208 |   @Xml.name("Metadata") metadata?: Record<string>;
        |                                    ^^^^^^^^^^^^^^
../C:/Users/caperal/repos/azure-rest-api-specs/node_modules/@typespec/compiler/lib/intrinsics.tsp:191:7 - warning @azure-tools/typespec-autorest/unsupported-param-type: Parameter can only be represented as primitive types in swagger 2.0. Information is lost for part 'x-ms-meta'.
> 191 | model Record<Element> {}
      |       ^^^^^^
  ../C:/Users/caperal/repos/azure-rest-api-specs/specification/storage/Microsoft.BlobStorage/models.tsp:208:36 - occurred while instantiating template
  > 208 |   @Xml.name("Metadata") metadata?: Record<string>;
        |                                    ^^^^^^^^^^^^^^
../C:/Users/caperal/repos/azure-rest-api-specs/node_modules/@typespec/compiler/lib/intrinsics.tsp:191:7 - warning @azure-tools/typespec-autorest/unsupported-param-type: Parameter can only be represented as primitive types in swagger 2.0. Information is lost for part 'metadata'.
> 191 | model Record<Element> {}
      |       ^^^^^^
  ../C:/Users/caperal/repos/azure-rest-api-specs/specification/storage/Microsoft.BlobStorage/models.tsp:208:36 - occurred while instantiating template
  > 208 |   @Xml.name("Metadata") metadata?: Record<string>;
        |                                    ^^^^^^^^^^^^^^
../C:/Users/caperal/repos/azure-rest-api-specs/node_modules/@typespec/compiler/lib/intrinsics.tsp:191:7 - warning @azure-tools/typespec-autorest/unsupported-param-type: Parameter can only be represented as primitive types in swagger 2.0. Information is lost for part 'metadata'.
> 191 | model Record<Element> {}
      |       ^^^^^^
  ../C:/Users/caperal/repos/azure-rest-api-specs/specification/storage/Microsoft.BlobStorage/models.tsp:208:36 - occurred while instantiating template
  > 208 |   @Xml.name("Metadata") metadata?: Record<string>;
        |                                    ^^^^^^^^^^^^^^
../C:/Users/caperal/repos/azure-rest-api-specs/node_modules/@typespec/compiler/lib/intrinsics.tsp:191:7 - warning @azure-tools/typespec-autorest/unsupported-param-type: Parameter can only be represented as primitive types in swagger 2.0. Information is lost for part 'x-ms-meta'.
> 191 | model Record<Element> {}
      |       ^^^^^^
  ../C:/Users/caperal/repos/azure-rest-api-specs/specification/storage/Microsoft.BlobStorage/models.tsp:208:36 - occurred while instantiating template
  > 208 |   @Xml.name("Metadata") metadata?: Record<string>;
        |                                    ^^^^^^^^^^^^^^
../C:/Users/caperal/repos/azure-rest-api-specs/node_modules/@typespec/compiler/lib/intrinsics.tsp:191:7 - warning @azure-tools/typespec-autorest/unsupported-param-type: Parameter can only be represented as primitive types in swagger 2.0. Information is lost for part 'x-ms-meta'.
> 191 | model Record<Element> {}
      |       ^^^^^^
  ../C:/Users/caperal/repos/azure-rest-api-specs/specification/storage/Microsoft.BlobStorage/models.tsp:208:36 - occurred while instantiating template
  > 208 |   @Xml.name("Metadata") metadata?: Record<string>;
        |                                    ^^^^^^^^^^^^^^
../C:/Users/caperal/repos/azure-rest-api-specs/node_modules/@typespec/compiler/lib/intrinsics.tsp:191:7 - warning @azure-tools/typespec-autorest/unsupported-param-type: Parameter can only be represented as primitive types in swagger 2.0. Information is lost for part 'x-ms-meta'.
> 191 | model Record<Element> {}
      |       ^^^^^^
  ../C:/Users/caperal/repos/azure-rest-api-specs/specification/storage/Microsoft.BlobStorage/models.tsp:208:36 - occurred while instantiating template
  > 208 |   @Xml.name("Metadata") metadata?: Record<string>;
        |                                    ^^^^^^^^^^^^^^
../C:/Users/caperal/repos/azure-rest-api-specs/node_modules/@typespec/compiler/lib/intrinsics.tsp:191:7 - warning @azure-tools/typespec-autorest/unsupported-param-type: Parameter can only be represented as primitive types in swagger 2.0. Information is lost for part 'x-ms-meta'.
> 191 | model Record<Element> {}
      |       ^^^^^^
  ../C:/Users/caperal/repos/azure-rest-api-specs/specification/storage/Microsoft.BlobStorage/models.tsp:208:36 - occurred while instantiating template
  > 208 |   @Xml.name("Metadata") metadata?: Record<string>;
        |                                    ^^^^^^^^^^^^^^
../C:/Users/caperal/repos/azure-rest-api-specs/node_modules/@typespec/compiler/lib/intrinsics.tsp:191:7 - warning @azure-tools/typespec-autorest/unsupported-param-type: Parameter can only be represented as primitive types in swagger 2.0. Information is lost for part 'x-ms-meta'.
> 191 | model Record<Element> {}
      |       ^^^^^^
  ../C:/Users/caperal/repos/azure-rest-api-specs/specification/storage/Microsoft.BlobStorage/models.tsp:208:36 - occurred while instantiating template
  > 208 |   @Xml.name("Metadata") metadata?: Record<string>;
        |                                    ^^^^^^^^^^^^^^

Found 20 warnings.
```

Since warnings are shown as errors in ci in the specs repo, this will block merging the PR. Spoke to @timotheeguerin who suggested the error might need to be moved in order to be able to suppress it in the spec.

### Reproduction

Link to spec: https://github.com/Azure/azure-rest-api-specs/tree/feature/blob-tsp/specification/storage/Microsoft.BlobStorage

Example definition causing the problem: 
- https://github.com/Azure/azure-rest-api-specs/blob/e5bdccbc8a36bb1eb1a94574c524d735f4762ddb/specification/storage/Microsoft.BlobStorage/models.tsp#L230

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [x] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by timotheeguerin** [comment]
I think for this specific error it should be emitted on teh parameter instead which would solve this specific case.

But more genericaly we have to decide how we can suppress those errors.

**Comment by markcowl** [comment]
closing as resolved by: https://github.com/Azure/typespec-azure/pull/2258

**Comment by catalinaperalta** [comment]
Reopening this issue, since it seems we still cant suppress the errors mentioned in the original issue. Here a more recent example of a failing pipeline run: https://github.com/Azure/azure-rest-api-specs/actions/runs/14578544278/job/40889958830?pr=32527#step:4:81

**Comment by timotheeguerin** [comment]
yea not sure what I fixed in the previous PR as this seems to repro https://azure.github.io/typespec-azure/playground/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7Cgp1c2luZyBIdHRwOwoKb3AgdGVzdDIoCiAgQHF1ZXJ5IGE%2FOiBSZWNvcmQ8c3RyaW5nPizEHWhlYWRlciBi0x4pOiB2b2lkOwo%3D&e=%40azure-tools%2Ftypespec-autorest&options=%7B%7D
