### ISSUE TITLE
Bug when using `@withVisibilityFilter` decorator and reusing models

### ISSUE THREAD

**Issue by lopezm94** [microsoft/typespec#7334]
I'm working on a use case where I need to use the decorator `@withVisibilityFilter` to filter models over different set of combinations of a custom visibility enum. However, I'm encountering issues with the decorator in general, whether it is using my own custom visibility enum or using the `Lifecycle` one. I have managed to reproduce one case where I have problems in a minimal example on the playground using the standard visibility.

```tsp
model Version {
  version: string;
}
model Property {
  @visibility(Lifecycle.Create)
  id: string;
  @visibility(Lifecycle.Read)
  version?: Version;
}
@withVisibilityFilter(#{any: #[Lifecycle.Read]})
model ReadProperty {
  ...Property
}
```
[Link to bug in playground](https://typespec.io/playground/?c=bW9kZWwgVmVyc2lvbiB7CiAgdsYMOiBzdHJpbmc7Cn0KxiVQcm9wZXJ0ecUmQHZpc2liaWxpdHkoTGlmZWN5Y2xlLkNyZWF0ZSkKICBpZMpB2C5SZWFkxCzHcj866ACIxHRAd2l0aFbJN0ZpbHRlcigje2FueTogI1vORl19KecApcQO7QCpLi4uyBAKfQ%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)

This is issue can be made to work in two ways. One is by embedding the definition of the `Version` model into property.
```tsp
model Property {
  @visibility(Lifecycle.Create)
  id: string;
  @visibility(Lifecycle.Read)
  version?: {
    version: string;
  };
}
@withVisibilityFilter(#{any: #[Lifecycle.Read]})
model ReadProperty {
  ...Property
}
```
[Link to "fix" in playground](https://typespec.io/playground/?c=bW9kZWwgUHJvcGVydHkgewogIEB2aXNpYmlsaXR5KExpZmVjeWNsZS5DcmVhdGUpCiAgaWQ6IHN0cmluZzvZLlJlYWTELHZlcnNpb24%2FOsVayRDMQX07Cn0KQHdpdGhWyUpGaWx0ZXIoI3thbnk6ICNbzlldfSkK5gC4xA7tALwuLi7IEAp9&e=%40typespec%2Fopenapi3&options=%7B%7D)

The second way to fix it is to use the decorator `@withVisibility` instead.
```tsp
model Version {
  version: string;
}
model Property {
  @visibility(Lifecycle.Create)
  id: string;
  @visibility(Lifecycle.Read)
  version?: Version;
}
@withVisibility(Lifecycle.Read)
model ReadProperty {
  ...Property
}
```
[Link to "fix" in playground](https://typespec.io/playground/?c=bW9kZWwgVmVyc2lvbiB7CiAgdsYMOiBzdHJpbmc7Cn0KxiVQcm9wZXJ0ecUmQHZpc2liaWxpdHkoTGlmZWN5Y2xlLkNyZWF0ZSkKICBpZMpB2C5SZWFkxCzHcj866ACIxHRAd2l0aFbaN%2BYAlMQM7QCYLi4uyBAKfQ%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)

Non of these "fixes" are attractive to my use case. I prefer not to use the 1st "fix" because I'll end up with big nested models that cannot be reused. And the second "fix" is for filtering use cases that are very simple, to give you an idea I created a custom visibility where I generate models using a visibility filter like this:
```tsp
// Properties that can be set during creation but cannot be changed
@withVisibilityFilter(#{ none: #[State.Generated] , any: #[State.Key, State.Immutable]})
model SettableOnlyDuringCreation<MODEL> {
  ...MODEL,
}
```

Is there an alternative way of representing this filter in a way that won't give me problems?

**Comment by timotheeguerin** [comment]
I think this has been fixed in main already and should be available in the next release of typespec(2-3 weeks), You can use the `next`(`-dev`) versions to try it out now. See the [next playground](https://cadlplayground.z22.web.core.windows.net/?c=bW9kZWwgVmVyc2lvbiB7CiAgdsYMOiBzdHJpbmc7Cn0KxiVQcm9wZXJ0ecUmQHZpc2liaWxpdHkoTGlmZWN5Y2xlLkNyZWF0ZSkKICBpZMpB2C5SZWFkxCzHcj866ACIxHRAd2l0aFbJN0ZpbHRlcigje2FueTogI1vORl19KecApcQO7QCpLi4uyBAKfQ%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)

**Comment by lopezm94** [comment]
Thanks @timotheeguerin! It does work for this small case scenario, however it is still happening on real case scenario. I'll reproduce the issue in a smaller format.
